export const CURRICULUM = {
  common: [
    { round: "1회차", title: "HTML / CSS 기초" },
    { round: "2회차", title: "Git 기초" },
    { round: "3회차", title: "Javascript 기초" },
    { round: "4회차", title: "AI 잘 다루는 법" },
    { round: "5회차", title: "WEB, HTTP, 기초 네트워크 지식" },
    { round: "6회차", title: "Database 기초" },
    { round: "7회차", title: "Json, API(문서화), HTTP Method, Postman" },
    { round: "8회차", title: "Figma 기초" },
  ],
  front: [
    { round: "1회차", title: "JS 심화(1)" },
    { round: "2회차", title: "JS 심화(2)" },
    { round: "3회차", title: "React 디렉토리 관리 + CSS 심화" },
    { round: "4회차", title: "React 컴포넌트, jsx, props" },
    { round: "5회차", title: "React state, 이벤트 처리" },
    { round: "6회차", title: "React hooks, effect, 생명 주기" },
    { round: "7회차", title: "React 라우팅, axios" },
    { round: "8회차", title: "API 연동" },
    { round: "9회차", title: "Vercel을 이용한 배포" },
  ],
  back: [
    { round: "1회차", title: "Java 기초 (1)" },
    { round: "2회차", title: "Java 기초 (2) & Spring Boot 입문" },
    { round: "3회차", title: "서버 구조 이해 & API 구현" },
    { round: "4회차", title: "데이터베이스 설계 & CRUD 구현" },
    { round: "5회차", title: "Spring Data JPA 활용 & API 문서화" },
    { round: "6회차", title: "S3를 활용한 게시글 업로드 기능 구현" },
    { round: "7회차", title: "인증·인가 기초" },
    { round: "8회차", title: "Validation, Exception 처리" },
    { round: "9회차", title: "서버 배포 경험" },
  ],
  design: [
    { round: "1회차", title: "OT + Figma, FigJam 기초" },
    { round: "2회차", title: "기획 프로세스 + 설문조사 유의점" },
    { round: "3회차", title: "서비스 소개 자료 만들기" },
    { round: "4회차", title: "Figma 심화" },
    { round: "5회차", title: "Figma Make + Figma Site" },
    { round: "6회차", title: "AI 활용하는 법" },
  ],
};
